version: "3"

services:
  app:
    build: .
    ports:
      - 4000:3000
    volumes:
      - ./:/var/app
    tty: true
    links:
      - db
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 4080:8080
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: barbershop
